### ISSUE TITLE
Incompatible location for gae.region and gcf.region in sample solution.yaml

### ISSUE THREAD

**Issue by alxdrl** [BrunoReboul/ram-config-template#104]
**Describe the bug**

Had to set location parameters for the Google App Engine (gae.region) and Google Cloud Function (gcf.region) in `solution.yaml` to the same value.

Indeed  App Engine instance has been created in `europe-west3` (even though the location parameter was `europe-west`) whereas the Cloud Function location was set to `europe-west1`

**To Reproduce**

Setup solution.yaml

```solution.yamk
  gae:
    region: europe-west
  gcf:
    region: europe-west3
```

Deploy pipeline with RAM CLI fails for some pipelines with the following error:

```log
Step #3 - "deploy instance dumpinventory_org675623659646_cloudresourcemanager_Folder": 2021/05/11 07:23:51 CloudSchedulerClient.GetJob rpc error: code = InvalidArgument desc = Location must equal europe-west3 because the App Engine app that is associated with this project is located in europe-west3
Finished Step #3 - "deploy instance dumpinventory_org675623659646_cloudresourcemanager_Folder"
ERROR
ERROR: build step 3 "gcr.io/cloud-builders/gcloud" failed: step exited with non-zero status: 1
```

**Expected behavior**

RAM CLI should check if the actual App Engine instance location is compatible with the Cloud Function location set in `solution.yaml` and emit a warning or error or merge the two location parameters.

**Comment by BrunoReboul** [comment]
Thanks for the feedback. RAMv1 is now deprecated, please use [RAMv2](https://gitlab.com/realtime-asset-monitor/setup)
