### ISSUE TITLE
[create new rule] gce_instance_service_account / no_default_service_account

### ISSUE THREAD

**Issue by BrunoReboul** [BrunoReboul/ram-config-template#64]
- @BrunoReboul 
  - [x] create an issue
- @MarcFundenberger
- [x] create topic branch named rulename 
- [x] create `.rego` rule file
- [x] create `.yaml` constraint file
- [x] create `readme.md`
- [x] Initiate PR
- @BrunoReboul 
- [ ] review PR, iterate
- [ ] create system tests, iterate
- [ ] merge to dev

**Comment by MarcFundenberger** [comment]
See PR #72
