### ISSUE TITLE
[create new rule] gce_network_name / no default_network

### ISSUE THREAD

**Issue by BrunoReboul** [BrunoReboul/ram-config-template#65]
- @BrunoReboul 
  - [x] create an issue
- @MarcFundenberger
  - [x] create topic branch named rulename 
  - [x] create `.rego` rule file
  - [x] create `.yaml` constraint file
  - [x] create `readme.md`
  - [x] Initiate PR
- @BrunoReboul 
  - [x] review PR, iterate
  - [x] create system tests, iterate
  - [x] merge to dev

**Comment by MarcFundenberger** [comment]
See PR #73
