### ISSUE TITLE
[create new rule] gci_group_settings external_members_denied_on_mailinglists + on secgroups + to_be_adapted

### ISSUE THREAD

**Issue by BrunoReboul** [BrunoReboul/ram-config-template#67]
- @BrunoReboul 
  - [x] create an issue
- @MarcFundenberger
- [x] create topic branch named rulename 
- [x] create `.rego` rule file
- [x] create `.yaml` constraint file
- [x] create `readme.md`
- [x] Initiate PR
- @BrunoReboul 
- [x] review PR, iterate
- [x] create system tests, iterate
- [x] merge to dev

**Comment by MarcFundenberger** [comment]
Distinction between security group and mailing list is based on group description only - the mailing list creation process ensure that the description follows some patterns... 
Do we want to have contraints based on that in our templates ?
